Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -11,20 +11,25 @@ jobs:
     steps:
       - name: Checkout Source
         uses: actions/checkout@v3
+
       - name: Login to Docker Hub
-        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
       - name: Build Docker Image
         run: docker build -t shetkarsupriya/reactjs-app .
-      - name: Publish image to docker hub
-        run: docker push shetkarsupriya/reactjs-app:latest   
 
-  deploy: 
+      - name: Publish image to docker hub
+        run: docker push shetkarsupriya/reactjs-app:latest
+
+  deploy:
     needs: build
-    runs-on: aws-ec2    
+    runs-on: aws-ec2
     steps:
       - name: Pull image from docker hub
-        run: docker pull shetkarsupriya/reactjs-app:latest 
+        run: docker pull shetkarsupriya/reactjs-app:latest
+
       - name: Delete Old Container
-        run: docker rm -f reactContainer
+        run: docker rm -f reactContainer || true  # won't fail if container doesn't exist
+
       - name: Run docker container
-        run: docker run -d -p 3000:80 --name reactContainer shetkarsupriya/reactjs-app   
+        run: docker run -d -p 3000:80 --name reactContainer shetkarsupriya/reactjs-app
